// Generated by CoffeeScript 1.7.1
(function() {
  var BaseView, CategoryListView, ItemDetailView, ItemListView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseView = (function(_super) {
    __extends(BaseView, _super);

    function BaseView() {
      return BaseView.__super__.constructor.apply(this, arguments);
    }

    return BaseView;

  })(Backbone.View);

  CategoryListView = (function(_super) {
    __extends(CategoryListView, _super);

    function CategoryListView() {
      return CategoryListView.__super__.constructor.apply(this, arguments);
    }

    return CategoryListView;

  })(BaseView);

  ItemListView = (function(_super) {
    __extends(ItemListView, _super);

    function ItemListView() {
      return ItemListView.__super__.constructor.apply(this, arguments);
    }

    return ItemListView;

  })(BaseView);

  ItemDetailView = (function(_super) {
    __extends(ItemDetailView, _super);

    function ItemDetailView() {
      return ItemDetailView.__super__.constructor.apply(this, arguments);
    }

    return ItemDetailView;

  })(BaseView);

}).call(this);
